version: '3.9'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 
      POSTGRES_DB: postgres
    labels:
      - "APP_DB_USERNAME=postgres"
      - "APP_DB_PASSWORD="
      - "APP_DB_NAME=postgres"
    ports:
      - "5432:5432"

  go:
    image: go
    depends_on:
      - postgres
    links:
      - postgres

  test:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - go
    links:
      - postgres
      - go
    command: ["go", "test"]